const names = ["Tiesha Thurlow"
    , "Rebbecca Reece"
    , "Kary Kosakowski"
    , "Jessie Jahnke"
    , "Ernie Estridge"
    , "Sharda Selley"
    , "Michale Mackson"
    , "Reginia Ruffino"
    , "Gilda Guard"
    , "Oren Ohanlon"
    , "Louella Leedom"
    , "Elvie Ekdahl"
    , "Amparo Alpaugh"
    , "Julee Jacobs"
    , "Georgette Gast"
    , "Burma Boatright"
    , "Dianna Diggins"
    , "Floyd Fortson"
    , "Teresia Trueblood"
    , "Goldie Gigliotti"
    , "Lashawnda Lentini"
    , "Felicia Fishburn"
    , "Buddy Boren"
    , "Jo Jeffers"
    , "Samara Starr"
    , "Vania Vecchio"
    , "Darlena Dryer"
    , "Danny Denzer"
    , "Dania Dunmore"
    , "Joan Jelley"
    , "Lovetta Lovell"
    , "Albertha Agar"
    , "Rolando Ruffin"
    , "Cinthia Choiniere"
    , "Russell Rickett"
    , "Meg Mchaney"
    , "Floy Felps"
    , "Grayce Garrow"
    , "Sammy Sinnott"
    , "Reta Ruiz"
    , "Stanton Schade"
    , "Margarette Melo"
    , "Audry Abelson"
    , "Loreta Langham"
    , "Loree Lively"
    , "Jayson Jagodzinski"
    , "Breana Buhler"
    , "Phylis Prager"
    , "Hilton Hawkins"
    , "Meri Menzie"];

function getRandomName() {
    return names[Math.floor(Math.random() * names.length)];
}

export default getRandomName;
// Make it mix and match later so theres 50 x 50 = 2500 total possible names